package com.mhw.journey.dto;
import java.time.LocalDateTime;
import java.util.List;
public class RecommendationResponse {
    private String type; private String city; private String weather; private String sourceStatus; private String querySummary; private String locationStatus; private LocalDateTime generatedAt; private List<Candidate> candidates;
    public RecommendationResponse(String type,String city,String weather,String sourceStatus,String querySummary,String locationStatus,LocalDateTime generatedAt,List<Candidate> candidates){this.type=type;this.city=city;this.weather=weather;this.sourceStatus=sourceStatus;this.querySummary=querySummary;this.locationStatus=locationStatus;this.generatedAt=generatedAt;this.candidates=candidates;}
    public String getType(){return type;} public String getCity(){return city;} public String getWeather(){return weather;} public String getSourceStatus(){return sourceStatus;} public String getQuerySummary(){return querySummary;} public String getLocationStatus(){return locationStatus;} public LocalDateTime getGeneratedAt(){return generatedAt;} public List<Candidate> getCandidates(){return candidates;}
    public static class Candidate { private Long id; private String title; private String city; private String category; private String bestSeason; private Integer score; private String reason; private String scoreBreakdown; private String sourceLabel; private String sourceUrl; private String estimate; private String district; private String address; private Double latitude; private Double longitude; private Double distanceKm; private Integer travelMinutes; private String travelDataStatus; private String navigationUrl;
        public Candidate(Long id,String title,String city,String category,String bestSeason,Integer score,String reason,String scoreBreakdown,String sourceLabel,String sourceUrl,String estimate,String district,String address,Double latitude,Double longitude,Double distanceKm,Integer travelMinutes,String travelDataStatus,String navigationUrl){this.id=id;this.title=title;this.city=city;this.category=category;this.bestSeason=bestSeason;this.score=score;this.reason=reason;this.scoreBreakdown=scoreBreakdown;this.sourceLabel=sourceLabel;this.sourceUrl=sourceUrl;this.estimate=estimate;this.district=district;this.address=address;this.latitude=latitude;this.longitude=longitude;this.distanceKm=distanceKm;this.travelMinutes=travelMinutes;this.travelDataStatus=travelDataStatus;this.navigationUrl=navigationUrl;}
        public Long getId(){return id;} public String getTitle(){return title;} public String getCity(){return city;} public String getCategory(){return category;} public String getBestSeason(){return bestSeason;} public Integer getScore(){return score;} public String getReason(){return reason;} public String getScoreBreakdown(){return scoreBreakdown;} public String getSourceLabel(){return sourceLabel;} public String getSourceUrl(){return sourceUrl;} public String getEstimate(){return estimate;} public String getDistrict(){return district;} public String getAddress(){return address;} public Double getLatitude(){return latitude;} public Double getLongitude(){return longitude;} public Double getDistanceKm(){return distanceKm;} public Integer getTravelMinutes(){return travelMinutes;} public String getTravelDataStatus(){return travelDataStatus;} public String getNavigationUrl(){return navigationUrl;}
    }
}
